#!/usr/bin/env bash

set -euo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/../../scripts/lib.sh"

export MIX_ENV=test

# Always install mix dependencies
cd /srv/philomena

step mix deps.get

# Run formatting check
step mix format --check-formatted

# Sleep to allow OpenSearch to finish initializing
# if it's not done doing whatever it does yet
step echo -n "Waiting for OpenSearch"

until step wget -qO - http://opensearch:9200; do
  sleep 2
done

# Create the database
step mix ecto.create
step mix ecto.load

# Test the application
step mix test "$@"

# Security lint
step mix sobelow --config
step mix deps.audit

# Static analysis
exec mix dialyzer
