#!/usr/bin/env sh
set -ex

export MIX_ENV=test

echo "PATH=$PATH"
echo "USER=$USER"

id

ls -lah /root || true
ls -lah /root/.cargo || true
ls -lah /root/.cargo/bin || true
ls -lah || true

echo !!!which cargo
which cargo

# Always install mix dependencies
(cd /srv/philomena && mix deps.get)

# Run formatting check
mix format --check-formatted

# Sleep to allow OpenSearch to finish initializing
# if it's not done doing whatever it does yet
printf "Waiting for OpenSearch"

until wget -qO - opensearch:9200; do
  printf "."
  sleep 2
done

echo

# Create the database
mix ecto.create
mix ecto.load

# Test the application
mix test

# Security lint
mix sobelow --config
mix deps.audit

# Static analysis
exec mix dialyzer
