#!/usr/bin/env bash
#
# Pre-commit hook to run lightweight checks and auto-format the code. It's designed
# to be blazingly fast, so it checks only changed files.
#
# You can install this hook and some of its dependencies by running `scripts/init.sh`.

set -euo pipefail

# Using `readlink` because the pre-commit hook is installed via a symlink, so
# we need to resolve it before we can make path relative to this script's file.
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../scripts/lib.sh"

files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

if [[ -z "$files" ]]; then
  info "No files changed. Exiting the pre-commit hook..."
  exit 0
fi

if command -v typos &> /dev/null; then
  echo "$files" | step xargs typos
else
  info "Skipping typos check, executable not found"
fi

if command -v shellcheck &> /dev/null; then
  ./scripts/shellcheck.sh
else
  info "Skipping shellcheck, executable not found"
fi

if command -v npx &> /dev/null; then
  echo "$files" | step xargs npx prettier --ignore-unknown --write
else
  info "Skipping prettier, npx not found"
fi

# `rustfmt` doesn't ignore non-rust files automatically
rust_files=$(echo "$files" | { grep -E '\.rs$' || true; })
if [[ -n "$rust_files" ]]; then
  if command -v cargo &> /dev/null; then
    echo "$rust_files" | step xargs cargo fmt --manifest-path native/Cargo.toml --
  else
    info "Skipping rustfmt, cargo not found"
  fi
fi

if command -v mix &> /dev/null; then
  echo "$files" | step xargs mix format
else
  info "Skipping mix format, mix not found"
fi

# Add the modified/prettified files to staging
echo "$files" | step xargs git add
