[package]
name = "mediaproc"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.20"
serde = { version = "1.0", features = ["derive"] }
tarpc = { version = "0.35", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
