name: Philomena Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-build-deps-${{ hashFiles('mix.lock') }}

      - run: docker-compose pull
      - run: docker-compose build

      - name: Build and test
        run: docker-compose run app run-test

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./assets

      - name: Run ESLint
        run: npm run lint
        working-directory: ./assets

      - name: Security lint
        run: |
          docker-compose run app mix sobelow --config
          docker-compose run app mix deps.audit
